spring.application.name=nba-play
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000}
anthropic.api.key=${ANTHROPIC_API_KEY}
